package orm.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import org.hibernate.annotations.Generated;

import java.time.LocalDateTime;
import java.util.Set;

@Entity // marks a class as a persistent entity in the database
// @Table(uniqueConstraints = @UniqueConstraint(columnNames = {"title"}));

public class Customer {
    @Id // marks the primary key property of an entity
    @Generated // marks a property as generated by the database
    String id;
    String username;
    String email;
    String password;
    Set<String> roles;
    LocalDateTime dateRegistered;

    @OneToMany(mappedBy = "customer") //
    Set<Comment> comment;

    @OneToMany(mappedBy = "customer") //
    Set<Recipe> recipe;
}
