package orm.entities;

import jakarta.persistence.*;
import org.hibernate.annotations.Generated;

import java.util.Set;

@Entity // marks a class as a persistent entity in the database
public class Ingredient {
    @Id // marks the primary key property of an entity
    @Generated // marks a property as generated by the database
    long id; // pk
    String name;
    long quantity;
    String unitOfMeasurement;

    //    @ManyToMany(mappedBy = "ingredients")
    //    @JoinColumn(name = "recipe_id")
    @ManyToMany
    @JoinTable(name = "ingredient_recipe",
            joinColumns = @JoinColumn(name = "ingredient_id"),
            inverseJoinColumns = @JoinColumn(name = "recipe_id"))
    Set<Recipe> recipes;

}
