package orm.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import org.hibernate.annotations.Generated;

@Entity // marks a class as a persistent entity in the database
public class Rating {
    @Id // marks the primary key property of an entity
    @Generated // marks a property as generated by the database
    String id;
    int value;
    String dateRated;



@ManyToOne(fetch = FetchType.LAZY)
    Recipe associatedRecipe;
    Customer rater;
}
