package orm.entities;

import jakarta.persistence.*;
import org.hibernate.annotations.Generated;

import java.time.LocalDateTime;
import java.util.Set;

@Entity // marks a class as a persistent entity in the database
public class Recipe {
    @Id // marks the primary key property of an entity
    @Generated // marks a property as generated by the database
    long id; // pk
    String title;
    String description;
    String instructions;
    String preparationTime;
    String cookingTime;
    int servings;
    String difficultyLevel;
    String rating;
    LocalDateTime dateCreated;
    LocalDateTime lastModified;
    //
//    @ManyToOne(fetch = FetchType.LAZY)
//    Customer creator;
    @ManyToMany(mappedBy = "recipes")
//    @JoinColumn(name = "ingredient_id")
    Set<Ingredient> ingredients;

//    @OneToMany
//    Set<Category> listOfCategories;
//    @OneToMany(mappedBy = "recipe") //
//    Set<Comment> comment;

}
